# this one is important
SET(CMAKE_SYSTEM_NAME Linux)
#this one not so much
SET(CMAKE_SYSTEM_VERSION 1)

# specify the cross compiler
SET(CMAKE_C_COMPILER        $ENV{ANDROID_TOOLCHAIN}/bin/arm-linux-androideabi-clang)
SET(CMAKE_CXX_COMPILER      $ENV{ANDROID_TOOLCHAIN}/bin/arm-linux-androideabi-clang++)
SET(CMAKE_FIND_ROOT_PATH    $ENV{ANDROID_TOOLCHAIN}/sysroot/usr/include)
# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(ANDROID_API $ENV{ANDROID_API})
SET(CMAKE_SYSTEM_PREFIX_PATH $ENV{SYSROOT}/usr)
SET(CMAKE_INSTALL_PREFIX $ENV{SYSROOT}/usr)

# SET(CMAKE_C_FLAGS "-fPIE -pie -D__ANDROID_API__=$ENV{ANDROID_API}")
# SET(CMAKE_CXX_FLAGS "-fPIE -pie -D__ANDROID_API__=$ENV{ANDROID_API} -std=c++11 -I$ENV{ANDROID_TOOLCHAIN}/include/c++/4.9.x")
# SET(CMAKE_SHARED_LINKER_FLAGS "-fPIE -pie")
# SET(CMAKE_EXE_LINKER_FLAGS ...)
# ANDROID_API=21
# CFLAGS=-fPIE -D__ANDROID_API__=$ENV{ANDROID_API}
# CPPFLAGS=-fPIE -D__ANDROID_API__=$ENV{ANDROID_API}
# LDFLAGS=-fPIE -pie -D__ANDROID_API__=$ENV{ANDROID_API}
